merge entrypoint and dockerfile

diff --git a/docker/Dockerfile b/docker/Dockerfile
--- a/docker/Dockerfile
+++ b/docker/Dockerfile
@@ -1,4 +1,4 @@
-FROM simonpzh/suse-slurm:20.11.9
+FROM ghcr.io/eth-cscs/slurm-container-20.11.9:latest
 
 RUN zypper install -y\
     fuse3-devel\
@@ -24,18 +24,20 @@ RUN zypper install -y\
     util-linux-systemd\
     psmisc\
     psutils\
-    strace
+    strace \
+    git
 
 # install meson and ninja via pip (packages are too old)
 RUN python3 -m pip install --upgrade pip && python3 -m pip install meson ninja
-RUN  wget https://github.com/vasi/squashfuse/archive/refs/tags/0.1.105.tar.gz && tar xf 0.1.105.tar.gz &&\
-    cd squashfuse-0.1.105 || exit 1 &&\
-    ./autogen.sh && ./configure --prefix=/usr/local && sudo make install
+RUN wget https://github.com/vasi/squashfuse/archive/refs/tags/0.1.105.tar.gz \
+    && tar xf 0.1.105.tar.gz \
+    && cd squashfuse-0.1.105 || exit 1 \
+    && ./autogen.sh && ./configure --prefix=/usr/local && sudo make install
 
-RUN --mount=type=bind,source=./,target=/CODE \
-    meson setup /build /CODE &&\
-    ninja install  -C /build  &&\
-    echo "required /usr/local/lib64/libslurm-uenv-mount.so" > /usr/local/etc/plugstack.conf
+RUN --mount=type=bind,source=../,target=/CODE \
+    CPPFLAGS=-I$SLURM_ROOT/include meson setup --prefix=$SLURM_ROOT /build /CODE \
+    && ninja install -C /build \
+    && echo "required $SLURM_ROOT/lib64/libslurm-uenv-mount.so" > $SLURM_ROOT/etc/plugstack.conf
 
 RUN mkdir /user-environment
 
@@ -44,6 +46,6 @@ RUN mkdir -p /home/testuser
 RUN chown testuser /home/testuser
 
 # USER testuser
-COPY docker/testuser-entrypoint.sh .
+COPY docker/testuser-entrypoint-jpc.sh .
 
-ENTRYPOINT ./testuser-entrypoint.sh
+ENTRYPOINT ./testuser-entrypoint-jpc.sh
