docker/ci

diff --git a/.github/workflows/slurm.yaml b/.github/workflows/slurm.yaml
--- a/.github/workflows/slurm.yaml
+++ b/.github/workflows/slurm.yaml
@@ -2,19 +2,57 @@ name: slurm
 #on: [push, pull_request]
 
 jobs:
-  makefile:
+  tests:
     runs-on: ubuntu-20.04
     container:
-      image: simonpzh/slurm-dkr2.suse
+      image: simonpzh/slurm-20.11.9
       # args: --entrypoint=./entrypoint.sh
     steps:
       - uses: actions/checkout@v2
-      - name: setup
+      - name: build
         run: |
-          # sudo apt-get install -y util-linux libmount-dev libfuse-dev libzstd-dev
-          # wget https://github.com/vasi/squashfuse/archive/refs/tags/0.1.105.tar.gz && tar xf 0.1.105.tar.gz
-          # cd squashfuse-0.1.105 || exit 1
-          # ./autogen.sh && ./configure --prefix=/usr && sudo make install
-          # check if slurmd is running
-          ps aux
+         zypper install -y python3-pip squashfs sudo
+         python3 -m pip install --upgrade pip \
+         && python3 -m pip install meson ninja
+
+         CPPFLAGS=-I$SLURM_ROOT/include meson setup builddir
+         ninja install -C builddir
+
+         echo "required /usr/local/lib64/libslurm-uenv-mount.so" \
+         > $SLURM_ROOT/etc/plugstack.conf
+
+         whoami
           # start slurm
+         /start-slurm.sh
+
+         # switch to testuser
+         set -x
+         useradd testuser
+         cat /etc/passwd
+         mkdir -p /home/testuser && chown -R testuser /home/testuser
+
+         # create a squashfs file
+         su testuser -c sh <<\EOF
+         dd=$(mktemp -d)
+         (
+             umask 022
+             cd "$dd" || exit
+             mkdir test
+             echo "This is file A" >> test/fileA.txt
+             mkdir -p test/testdir
+         )
+         mksquashfs "$dd" /home/testuser/fs.sqfs -noappend
+         EOF
+
+         mkdir -p /user-environment
+
+      - name: check
+        run: |
+          sudo -u testuser sinfo
+
+      - name: mount
+        run: |
+          su testuser -c sh <<\EOF
+          srun --uenv-mount-file=/home/testuser/fs.sqfs stat \
+          /user-environment/test/fileA.txt
+          EOF
